[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64", "setuptools-scm>=8"]

[tool.setuptools_scm]
root = "../../.."


[project]
name = "agentiq-agno"
dynamic = ["version"]
dependencies = [
  "aiqtoolkit[agno]~=1.2"
]
readme = "pypi.md"
description = "Transitional package for aiqtoolkit-agno, this package is deprecated and will be removed in the future."
classifiers = ["Programming Language :: Python"]
