[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64", "setuptools-scm>=8"]


[tool.setuptools_scm]
root = "../../.."

[project]
name = "agentiq-mem0ai"
dynamic = ["version"]
dependencies = [
  "aiqtoolkit[mem0ai]~=1.2"
]
readme = "pypi.md"
description = "Transitional package for aiqtoolkit-mem0ai, this package is deprecated and will be removed in the future."
classifiers = ["Programming Language :: Python"]
